### PR TITLE
Update integration headers w/new artwork

### PR DESCRIPTION
**Pull request by rossturk**
Signed-off-by: Ross Turk <ross@rossturk.com>

Added some new headers for the integration pages, based off of the brand colors of the neighboring technology. Not going to win any prizes here, but they look better than what's there today :)

Screenshots:
Screen Shot 2021-09-09 at 1 22 53 AM
Screen Shot 2021-09-09 at 1 22 41 AM

### CODE REVIEW

**Comment by rossturk** [comment]
I am sneaking an updated architecture diagram into this PR:

Screen Shot 2021-09-09 at 11 54 43 AM

**Comment by collado-mike** [comment]
I truly love the Airflow one. The Spark one is a bit dark, though. Any way to make it orange and white rather than black? Or will that look weird?
image

**Comment by rossturk** [comment]
> I truly love the Airflow one. The Spark one is a bit dark, though. Any way to make it orange and white rather than black? Or will that look weird?

@collado-mike it has to work with white text on top of it, unfortunately, unless I make some sort of text color override in the page metadata. let me try orange in the center and white at the edges and see if its any better. I agree, this one screams halloween.

**Comment by rossturk** [comment]
@collado-mike how's this? if you are +1 I will throw in the add'l commit

Screen Shot 2021-09-09 at 12 04 53 PM

**Comment by collado-mike** [comment]
> this one screams halloween.

😂

**Comment by collado-mike** [comment]
I like it a lot better

**Pull request merged**
