### PR TITLE
add ecosystem page with current set of logos

### PR DESCRIPTION
**Pull request by merobi-hub**
This change would add an Ecosystem basepage with a table of metadata producers and consumers.

Signed-off-by: Michael Robinson <merobi@gmail.com>

### CODE REVIEW

**Comment by merobi-hub** [comment]
@rossturk This is ready for review

**Comment by merobi-hub** [comment]
@rossturk This is ready for review

**Comment by merobi-hub** [comment]
@rossturk we're getting there, I think. The different stroke on the borders on the bottom is actually a resolution issue, not a stroke issue

**Comment by merobi-hub** [comment]
@rossturk This RFR. Please note the way I resolved a conflict in `config.ts` in case you would prefer a different order for the basepages there.

**Review by rossturk — APPROVED** [review]

**Pull request merged**
